services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: family-budget-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/family_budget
      - AUTH_SECRET=dev-secret-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      db:
        condition: service_healthy
    networks:
      - family-budget-network

  db:
    image: postgres:16-alpine
    container_name: family-budget-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=family_budget
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - family-budget-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  family-budget-network:
    driver: bridge
