services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: family-budget-app
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/family_budget
      - AUTH_SECRET=dev-secret-change-in-production
      - NEXTAUTH_URL=http://localhost:3000
      # Mailpit SMTP settings for local development
      - SMTP_HOST=mailpit
      - SMTP_PORT=1025
      - EMAIL_FROM=Family Budget <noreply@familybudget.local>
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
    networks:
      - family-budget-network

  db:
    image: postgres:16-alpine
    container_name: family-budget-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=family_budget
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - family-budget-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: family-budget-mailpit
    ports:
      - '8025:8025'  # Web UI
      - '1025:1025'  # SMTP
    environment:
      - MP_SMTP_AUTH_ACCEPT_ANY=true
      - MP_SMTP_AUTH_ALLOW_INSECURE=true
    networks:
      - family-budget-network

volumes:
  postgres_data:
  node_modules:
  next_cache:

networks:
  family-budget-network:
    driver: bridge
