# fly.toml app configuration file generated for family-budget-app on 2025-08-06T00:41:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'family-budget-app'
primary_region = 'yyz'

[build]

[deploy]
  release_command = 'node node_modules/prisma/build/index.js migrate deploy'
  seed_command = 'tsx prisma/seed.ts'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = "2gb"